### ISSUE TITLE
issues installing extendastory latest version

### ISSUE THREAD

**Issue by reaibn** [extend-a-story/extend-a-story#3]
I am using MySQL 5.7 (also tried with 5.5) and cannot get extend-a-story to work. It just shows  this error:

![image](https://user-images.githubusercontent.com/51311338/58778913-e16cb880-8599-11e9-86ff-0539a62e4325.png)

What am i missing? I followed your readme, although I did have to use the db.php from the older installation of extend-a-story so maybe it doesnt use that anymore? If i need to follow other instructions just let me know. Thanks for your time. 

I am pretty sure the problem is that the readme told me to modify db.php but there was no db.php.

**Comment by reaibn** [comment]
Should I be putting information into the Configuration.php instead?

**Comment by jjweston** [comment]
Hello! It looks like you are trying to use the latest commit of Extend-A-Story available in GitHub instead of a released version. Extend-A-Story development is ongoing and the latest commit in GitHub is not suitable for use on a production web site. Version 2.2.1 of Extend-A-Story is the most recent release. Please use that.

https://github.com/extend-a-story/extend-a-story/releases/tag/2.2.1

**Comment by reaibn** [comment]
That worked! Thank you so much, sorry I made such a silly mistake.
